"""empty message

Revision ID: 2326e4cdd2df
Revises: 
Create Date: 2020-10-25 14:18:15.660081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2326e4cdd2df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actors', 'fname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'lname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'release',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'release',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'lname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'fname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
